# Generated by Django 6.0.7 on 2026-07-28 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('encuentro', models.CharField(db_index=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('ciudad_eeuu', models.CharField(blank=True, max_length=150, null=True)),
                ('ciudad_mx', models.CharField(blank=True, max_length=150, null=True)),
                ('total', models.IntegerField(default=0)),
                ('mexico', models.IntegerField(default=0)),
                ('extranjeros', models.IntegerField(default=0)),
                ('desglose_nacionalidades', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['fecha', 'encuentro'], name='carga_encue_fecha_527931_idx')],
            },
        ),
        migrations.CreateModel(
            name='EstadoOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinturon', models.IntegerField(blank=True, null=True)),
                ('ceco', models.CharField(blank=True, max_length=100, null=True)),
                ('frontera_norte', models.BooleanField(default=False)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Caravana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True)),
                ('anio', models.IntegerField(db_index=True)),
                ('lugar_partida', models.CharField(blank=True, max_length=250, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('lugar_disolucion', models.CharField(blank=True, max_length=250, null=True)),
                ('personas_inicio', models.IntegerField(default=0)),
                ('personas_rescatadas', models.IntegerField(default=0)),
                ('personas_documentadas', models.IntegerField(default=0)),
                ('personas_trasladadas', models.IntegerField(default=0)),
                ('tipo_documento', models.CharField(blank=True, max_length=250, null=True)),
                ('tvrh', models.IntegerField(default=0)),
                ('pam', models.IntegerField(default=0)),
                ('fmm', models.IntegerField(default=0)),
                ('cita_comar', models.IntegerField(default=0)),
                ('docs_provisionales', models.IntegerField(default=0)),
                ('desglose_nacionalidades', models.JSONField(default=dict)),
                ('estado_disolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caravanas_disolucion', to='carga.estadoor')),
                ('estado_partida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caravanas_partida', to='carga.estadoor')),
            ],
            options={
                'indexes': [models.Index(fields=['dia', 'nombre'], name='carga_carav_dia_a9ff97_idx')],
            },
        ),
        migrations.CreateModel(
            name='MexicanoRecibido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True)),
                ('total', models.IntegerField(default=0)),
                ('adultos', models.IntegerField(default=0)),
                ('menores', models.IntegerField(default=0)),
                ('nna_no_acompanados', models.IntegerField(default=0)),
                ('nna_acompanados', models.IntegerField(default=0)),
                ('terrestres', models.IntegerField(default=0)),
                ('vuelos', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estadoor')),
            ],
            options={
                'indexes': [models.Index(fields=['dia', 'estado'], name='carga_mexic_dia_ee3bc3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MotivoEstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True)),
                ('motivo_estancia', models.CharField(blank=True, max_length=250, null=True)),
                ('documentos_migratorios', models.IntegerField(default=0)),
                ('tarjeta_residente_permanente', models.IntegerField(default=0)),
                ('tarjeta_residente_temporal', models.IntegerField(default=0)),
                ('tarjeta_residente_temporal_estudiante', models.IntegerField(default=0)),
                ('tarjeta_visitante_razones_humanitarias', models.IntegerField(default=0)),
                ('tarjeta_visitante_adopcion', models.IntegerField(default=0)),
                ('tarjeta_visitante_regional', models.IntegerField(default=0)),
                ('tarjeta_visitante_trabajador_fronterizo', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estadoor')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.nacionalidad')),
            ],
            options={
                'indexes': [models.Index(fields=['dia', 'estado', 'nacionalidad'], name='carga_motiv_dia_9d59c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Internacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True)),
                ('total', models.IntegerField(default=0)),
                ('aereo', models.IntegerField(default=0)),
                ('maritimo', models.IntegerField(default=0)),
                ('terrestre', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estadoor')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.nacionalidad')),
            ],
            options={
                'indexes': [models.Index(fields=['dia', 'estado', 'nacionalidad'], name='carga_inter_dia_580228_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inadmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True)),
                ('total', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estadoor')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.nacionalidad')),
            ],
            options={
                'indexes': [models.Index(fields=['dia', 'estado', 'nacionalidad'], name='carga_inadm_dia_767e5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExtranjeroRecibido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True)),
                ('total', models.IntegerField(default=0)),
                ('adultos', models.IntegerField(default=0)),
                ('menores', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estadoor')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.nacionalidad')),
            ],
            options={
                'indexes': [models.Index(fields=['dia', 'estado', 'nacionalidad'], name='carga_extra_dia_1b6f28_idx')],
            },
        ),
        migrations.CreateModel(
            name='CondicionEstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True)),
                ('documentos_migratorios', models.IntegerField(default=0)),
                ('tarjeta_residente_permanente', models.IntegerField(default=0)),
                ('tarjeta_residente_temporal', models.IntegerField(default=0)),
                ('tarjeta_residente_temporal_estudiante', models.IntegerField(default=0)),
                ('tarjeta_visitante_razones_humanitarias', models.IntegerField(default=0)),
                ('tarjeta_visitante_adopcion', models.IntegerField(default=0)),
                ('tarjeta_visitante_regional', models.IntegerField(default=0)),
                ('tarjeta_visitante_trabajador_fronterizo', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estadoor')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.nacionalidad')),
            ],
            options={
                'indexes': [models.Index(fields=['dia', 'estado', 'nacionalidad'], name='carga_condi_dia_53374e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CanalizadoNNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True)),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True)),
                ('nombres', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_salida', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estadoor')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.nacionalidad')),
            ],
            options={
                'indexes': [models.Index(fields=['dia', 'estado', 'nacionalidad'], name='carga_canal_dia_ff9af2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CanalizadoAdulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True)),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True)),
                ('nombres', models.CharField(blank=True, max_length=200, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo_salida', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estadoor')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.nacionalidad')),
            ],
            options={
                'indexes': [models.Index(fields=['dia', 'estado', 'nacionalidad'], name='carga_canal_dia_ca4d2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Presentado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True)),
                ('estacion_migratoria', models.CharField(blank=True, max_length=250, null=True)),
                ('total', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estadoor')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.nacionalidad')),
            ],
            options={
                'indexes': [models.Index(fields=['dia', 'estado', 'nacionalidad'], name='carga_prese_dia_d40ce2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rescatado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True)),
                ('total', models.IntegerField(default=0)),
                ('primera_vez', models.IntegerField(default=0)),
                ('reincidencia', models.IntegerField(default=0)),
                ('presentados_em', models.IntegerField(default=0)),
                ('canalizados_dif', models.IntegerField(default=0)),
                ('conduccion_norte_sur', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estadoor')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.nacionalidad')),
            ],
            options={
                'indexes': [models.Index(fields=['dia', 'estado', 'nacionalidad'], name='carga_resca_dia_da4709_idx')],
            },
        ),
        migrations.CreateModel(
            name='Retornado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True)),
                ('total', models.IntegerField(default=0)),
                ('deportados', models.IntegerField(default=0)),
                ('retornos_asistidos', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estadoor')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.nacionalidad')),
            ],
            options={
                'indexes': [models.Index(fields=['dia', 'estado', 'nacionalidad'], name='carga_retor_dia_175dd8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True)),
                ('total', models.IntegerField(default=0)),
                ('estado_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_destino', to='carga.estadoor')),
                ('estado_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_origen', to='carga.estadoor')),
            ],
            options={
                'indexes': [models.Index(fields=['dia', 'estado_origen', 'estado_destino'], name='carga_trasl_dia_93134e_idx')],
            },
        ),
    ]
