# Generated by Django 6.0.7 on 2026-07-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadoor',
            name='frontera_norte',
        ),
        migrations.AddField(
            model_name='estadoor',
            name='frontera',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
