# Generated by Django 6.0.7 on 2026-07-30 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0002_remove_estadoor_frontera_norte_estadoor_frontera'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canalizadoadulto',
            options={'verbose_name': 'Adulto Canalizado', 'verbose_name_plural': 'Adultos Canalizados'},
        ),
        migrations.AlterModelOptions(
            name='canalizadonna',
            options={'verbose_name': 'NNA Canalizado', 'verbose_name_plural': 'NNAs Canalizados'},
        ),
        migrations.AlterModelOptions(
            name='condicionestancia',
            options={'verbose_name': 'Condicion de Estancia', 'verbose_name_plural': 'Condicion de Estancia'},
        ),
        migrations.AlterModelOptions(
            name='encuentro',
            options={'verbose_name': 'Encuentros', 'verbose_name_plural': 'Encuentros'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='estadoor',
            options={'verbose_name': 'OR y Estado', 'verbose_name_plural': 'OR y Estados'},
        ),
        migrations.AlterModelOptions(
            name='inadmision',
            options={'verbose_name': 'Inadmision', 'verbose_name_plural': 'Inadmisiones'},
        ),
        migrations.AlterModelOptions(
            name='internacion',
            options={'verbose_name': 'Internacion', 'verbose_name_plural': 'Internaciones'},
        ),
        migrations.AlterModelOptions(
            name='motivoestancia',
            options={'verbose_name': 'Motivo de Estancia', 'verbose_name_plural': 'Motivos de Estancia'},
        ),
        migrations.AlterModelOptions(
            name='nacionalidad',
            options={'verbose_name': 'Nacionalidad', 'verbose_name_plural': 'Nacionalidades'},
        ),
        migrations.AlterModelOptions(
            name='presentado',
            options={'verbose_name': 'Presentados', 'verbose_name_plural': 'Presentados'},
        ),
        migrations.AlterModelOptions(
            name='rescatado',
            options={'verbose_name': 'Rescatado', 'verbose_name_plural': 'Rescatados'},
        ),
        migrations.CreateModel(
            name='ActasCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(db_index=True)),
                ('oficina', models.CharField(blank=True, max_length=100, null=True)),
                ('nut', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo_tramite', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_acto', models.CharField(blank=True, max_length=50, null=True)),
                ('no_acta', models.CharField(blank=True, max_length=50, null=True)),
                ('oficialia', models.CharField(blank=True, max_length=50, null=True)),
                ('libro', models.CharField(blank=True, max_length=50, null=True)),
                ('entidad', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('validacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estado')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.nacionalidad')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
    ]
