# Generated by Django 5.2.16 on 2026-07-30 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0003_alter_canalizadoadulto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actascivil',
            options={'verbose_name': 'Acta Civil', 'verbose_name_plural': 'Actas Civiles'},
        ),
    ]
