# Generated by Django 6.0.7 on 2026-07-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0004_alter_actascivil_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actascivil',
            name='nut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
