# Generated by Django 6.0.7 on 2026-07-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0005_alter_actascivil_nut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actascivil',
            name='nut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
