# Generated by Django 5.2.16 on 2026-07-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0006_alter_actascivil_nut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actascivil',
            name='libro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actascivil',
            name='no_acta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actascivil',
            name='nut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actascivil',
            name='oficialia',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='actascivil',
            name='tipo_acto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
