# Generated by Django 6.0.7 on 2026-07-31 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0007_alter_actascivil_libro_alter_actascivil_no_acta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TramitesMigratorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('oficina', models.CharField(blank=True, max_length=100, null=True)),
                ('tramite', models.CharField(blank=True, max_length=100, null=True)),
                ('recibidos', models.IntegerField(default=0)),
                ('concluidos', models.IntegerField(default=0)),
                ('resueltos', models.IntegerField(default=0)),
                ('resueltos_dentro_plazo', models.IntegerField(default=0)),
                ('resueltos_fuera_plazo', models.IntegerField(default=0)),
                ('proceso', models.IntegerField(default=0)),
                ('proceso_dentro_plazo', models.IntegerField(default=0)),
                ('proceso_fuera_plazo', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estado')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.nacionalidad')),
            ],
            options={
                'verbose_name': 'Tramites Migratorios',
                'verbose_name_plural': 'Tramites Migratorios',
            },
        ),
    ]
