# Generated by Django 6.0.7 on 2026-08-05 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0008_tramitesmigratorios'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIngresoP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Ingreso',
                'verbose_name_plural': 'Tipos de Ingreso',
            },
        ),
        migrations.CreateModel(
            name='Inadmision2da',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True)),
                ('puntoInternacion', models.CharField(blank=True, max_length=100, null=True)),
                ('determinacion', models.CharField(db_index=True, max_length=150, unique=True)),
                ('total', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estadoor')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.nacionalidad')),
            ],
            options={
                'verbose_name': 'Inadmision',
                'verbose_name_plural': 'Inadmisiones',
                'indexes': [models.Index(fields=['dia', 'estado', 'puntoInternacion', 'determinacion', 'nacionalidad'], name='carga_inadm_dia_9f7d1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternacionN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True)),
                ('puntoInternacion', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.IntegerField(default=0)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.estadoor')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.nacionalidad')),
                ('tipoIngreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carga.tipoingresop')),
            ],
            options={
                'verbose_name': 'Internacion Nuevo',
                'verbose_name_plural': 'Internaciones N',
                'indexes': [models.Index(fields=['dia', 'estado', 'tipoIngreso', 'puntoInternacion', 'nacionalidad'], name='carga_inter_dia_b083a8_idx')],
            },
        ),
    ]
