# Generated by Django 6.0.7 on 2026-08-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0009_tipoingresop_inadmision2da_internacionn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inadmision2da',
            name='determinacion',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='inadmision2da',
            name='puntoInternacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='internacionn',
            name='puntoInternacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
