# Generated by Django 6.1 on 2026-08-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0010_alter_inadmision2da_determinacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inadmision2da',
            options={'verbose_name': 'Inadmision 2da Rev', 'verbose_name_plural': 'Inadmisiones 2da Rev'},
        ),
        migrations.CreateModel(
            name='MetricaComparativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(db_index=True, max_length=150)),
                ('subcategoria', models.CharField(db_index=True, max_length=150)),
                ('anio', models.IntegerField(db_index=True)),
                ('valor_numero', models.BigIntegerField(blank=True, null=True)),
                ('valor_texto', models.CharField(blank=True, max_length=255, null=True)),
                ('datos_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Métrica Comparativa',
                'verbose_name_plural': 'Métricas Comparativas',
                'indexes': [models.Index(fields=['categoria', 'subcategoria', 'anio'], name='carga_metri_categor_ed541d_idx')],
            },
        ),
    ]
