# Generated by Django 6.1.1 on 2026-09-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0011_alter_inadmision2da_options_metricacomparativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MexRepatriados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('oficina', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('puntoInternación', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('total', models.IntegerField(default=0)),
                ('hombresA', models.IntegerField(default=0)),
                ('mujeresA', models.IntegerField(default=0)),
                ('ninos', models.IntegerField(default=0)),
                ('ninas', models.IntegerField(default=0)),
                ('acompañados', models.IntegerField(default=0)),
                ('solos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mex Repatriado',
                'verbose_name_plural': 'Mex Repatriados',
            },
        ),
    ]
