# Generated by Django 6.1.1 on 2026-09-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0012_mexrepatriados'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepatriadosComerciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('oficina', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('puntoInternación', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('total', models.IntegerField(default=0)),
                ('adultos', models.IntegerField(default=0)),
                ('menores', models.IntegerField(default=0)),
                ('nna_acompañados', models.IntegerField(default=0)),
                ('nna_solos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Repatriado V. Comercial',
                'verbose_name_plural': 'Repatriados V. Comercial',
            },
        ),
    ]
