# Generated by Django 6.1.1 on 2026-09-25 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dg', models.CharField(max_length=150, verbose_name='Nombre Dirección General')),
                ('abreviatura_dg', models.CharField(max_length=10, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'Dirección General',
                'verbose_name_plural': 'Direcciones Generales',
            },
        ),
        migrations.CreateModel(
            name='UsuarioS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('tipo', models.CharField(choices=[('1', 'Administrador'), ('2', 'Editor'), ('3', 'Visualizador')], default='2', max_length=1, verbose_name='Tipo de Usuario')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuario.direccion', verbose_name='Área / Dirección')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Autenticación')),
            ],
            options={
                'verbose_name': 'Usuario Sistema',
                'verbose_name_plural': 'Usuarios Sistema',
            },
        ),
    ]
